DROP DATABASE IF EXISTS SONGDB;

CREATE DATABASE SONGDB;

USE SONGDB;

CREATE TABLE USER(
USER_ID INT NOT NULL AUTO_INCREMENT,
USER_EMAIL VARCHAR(255) UNIQUE NOT NULL, 
USER_PASS VARCHAR(255) NOT NULL,
PRIMARY KEY(USER_ID)
);

CREATE TABLE SONG(
SONG_ID INT NOT NULL AUTO_INCREMENT,
USER_ID INT NOT NULL,
SONG_NAME VARCHAR(255) NOT NULL,
PRIMARY KEY(SONG_ID),
FOREIGN KEY(USER_ID) REFERENCES USER (USER_ID)
);



